### ISSUE TITLE
将SwiftSVGAPlayer引入工程报错，求大神帮忙！谢谢！

### ISSUE THREAD

**Issue by ETmanwenhan** [janlionly/SwiftySVGAPlayer#1]
dyld: Library not loaded: @rpath/SSZipArchive.framework/SSZipArchive
  Referenced from: /private/var/containers/Bundle/Application/839AE8BC-C1AA-48F3-90FF-8CE7C5F26875/hohoyy.app/Frameworks/SwiftySVGAPlayer.framework/SwiftySVGAPlayer
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**Comment by ETmanwenhan** [comment]
直接运行SVGADemo也是报错哦！

module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3.2 compiler: /Users/andy/Documents/git_repo/demo/SwiftySVGAPlayer-master/SwiftySVGAPlayer.framework/Modules/SwiftySVGAPlayer.swiftmodule/arm64-apple-ios.swiftmodule

![image](https://user-images.githubusercontent.com/5837888/115505015-6e62ad00-a2ab-11eb-9759-b3f936d5d82b.png)

**Comment by janlionly** [comment]
Fixed it. Please run 'pod install' in your terminal and then run demo on your iOS device(not simulator).
